### PR TITLE
Add pts = 'points'

### LINKED ISSUE #29: Add `points` alias, to be used with PG()
If you want to use PG(), 'points' is quite verbose. `[p]` perhaps?

Edit: Similarly 'fill' and 'stroke' could do with aliases.

### PR DESCRIPTION
**Pull request by owennw**
Closes #29

### CODE REVIEW

**Comment by chrisprice** [comment]
Do you want to add stroke and fill as well?

**Comment by owennw** [comment]
Yeah sure.

**Comment by owennw** [comment]
Updated.

**Comment by chrisprice** [comment]
Thanks!

**Pull request merged**
